### ISSUE TITLE
Demo在iOS9+上运行有问题

### ISSUE THREAD

**Issue by yuhanle** [music4kid/CDD#1]
运行成功后，点击demo直接崩溃，提示信息是约束问题

2016-02-22 13:24:55.435 CDDDemo[9981:560723] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* +[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:]: A constraint cannot be made between a leading/trailing attribute and a right/left attribute. Use leading/trailing for both or neither.'
**\* First throw call stack:
(
    0   CoreFoundation                      0x0000000111856e65 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x00000001112cfdeb objc_exception_throw + 48
    2   CoreFoundation                      0x0000000111856d9d +[NSException raise:format:] + 205
    3   Foundation                          0x000000010f5418e2 +[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:] + 299
    4   CDDDemo                             0x000000010f3e53da -[MASViewConstraint install] + 954
    5   CDDDemo                             0x000000010f3e012f -[MASConstraintMaker install] + 1055
    6   CDDDemo                             0x000000010f3eb7ab -[UIView(MASAdditions) mas_makeConstraints:] + 155
    7   CDDDemo                             0x000000010f3ce953 -[UIView(MASShorthandAdditions) makeConstraints:] + 67
    8   CDDDemo                             0x000000010f3cf521 -[MessageCellText doMessageRendering] + 353
    9   CDDDemo                             0x000000010f3ca8ff -[CDDDemoView tableView:cellForRowAtIndexPath:] + 591
    10  UIKit                               0x000000010ff05e43 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 766
    11  UIKit                               0x000000010ff05f7b -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 74
    12  UIKit                               0x000000010fedaa39 -[UITableView _updateVisibleCellsNow:isRecursive:] + 2996
    13  UIKit                               0x000000010ff0f01c -[UITableView _performWithCachedTraitCollection:] + 92
    14  UIKit                               0x000000010fef5edc -[UITableView layoutSubviews] + 224
    15  UIKit                               0x000000010fe634a3 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 703
    16  QuartzCore                          0x0000000111f1e59a -[CALayer layoutSublayers] + 146
    17  QuartzCore                          0x0000000111f12e70 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
    18  QuartzCore                          0x0000000111f12cee _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
    19  QuartzCore                          0x0000000111f07475 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
    20  QuartzCore                          0x0000000111f34c0a _ZN2CA11Transaction6commitEv + 486
    21  QuartzCore                          0x0000000111f3537c _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 92
    22  CoreFoundation                      0x0000000111782367 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION** + 23
    23  CoreFoundation                      0x00000001117822d7 __CFRunLoopDoObservers + 391
    24  CoreFoundation                      0x0000000111777f2b __CFRunLoopRun + 1147
    25  CoreFoundation                      0x0000000111777828 CFRunLoopRunSpecific + 488
    26  GraphicsServices                    0x0000000114d3aad2 GSEventRunModal + 161
    27  UIKit                               0x000000010fdac610 UIApplicationMain + 171
    28  CDDDemo                             0x000000010f3d322f main + 111
    29  libdyld.dylib                       0x0000000112ead92d start + 1
    30  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by JAKILL1997** [comment]
高峰 快来解释一下，这个确实一运行就崩溃了

**Comment by music4kid** [comment]
已修复。

**Comment by yuhanle** [comment]
@music4kid tks
