### ISSUE TITLE
十分支持这个架构模式

### ISSUE THREAD

**Issue by xuzhongping** [music4kid/CDD#2]
基本看完了里面代码，我觉得要比目前的MVVM要强很多，非常好的解决了层级深的view的跨多层事件传递，未来的项目将尝试一下！👍

**Comment by dengchaojie** [comment]
![image](https://user-images.githubusercontent.com/13744851/32206899-44e556d0-bdc6-11e7-9fbe-1960554eafc2.png)
为什么姓名的改变放到KVO里，而头像和内容的改变，没有这样做？
